<?php

// added html elements and css classes to them:
//  content-container(8),newsletter-wrapper(9),newsletter-title(10),descr-newsletter(12)

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="content-container">
        <div class="newsletter-wrapper">
            <div class="newsletter-title">
                <h2>keep updated</h2>
                <div class="descr-newsletter"><?= $block->escapeHtml(__('Sign up for our newletter to recevie updates an exlusive offers')) ?></div>
            </div>
            <div class="content">
                <form class="form subscribe" novalidate action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
                    <div class="field newsletter">
                        <div class="control">
                            <label for="newsletter">
                                <span class="label">
                                    <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                                </span>
                                <input name="email" type="email" id="newsletter" placeholder="<?= $block->escapeHtml(__('TEST CHANGE')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" />
                            </label>
                        </div>
                    </div>
                    <div class="actions">
                        <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit" aria-label="Subscribe">
                            <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>