<?php
use Magento\Framework\App\Action\Action;

/** 43-44 image hover variables */
/** 57-109 added image hover container with content for grid-view */
/** 119-130 description moved under product title */
/** 177-189 added if to remove duplicated actions-secondary on list-view */
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $_imageHelper = $this->helper("Magento\Catalog\Helper\Image");
    $_imageHover = "hover_product_list"; /** adding hover for images */
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">

                    <div class="hover-container">   
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        $productImageHover = $_imageHelper->init($_product, $_imageHover);
                        if ($viewMode === 'grid'): ?>

                         <?php // Product Image ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>" class="product-item-photo">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <?php //Product Image Hovered ?>
                            <?php if (strpos($productImageHover->getUrl(), "Magento_Catalog/images/product/placeholder/hover.jpg") == false) : ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>" class="product-item-photo-hovered">
                                    <?= $block->getImage($_product, $_imageHover)->toHtml() ?>
                                </a>
                            <?php endif; ?>
                    
                            <div data-role="add-to-links" class="actions-secondary">
                                <ul class="add-to-links">
                                    <li>
                                        <a href="#" class="action quick-view"> 
                                        <i class="fas fa-eye"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="action to-wish-list" data-action="add-to-wishlist">
                                        <i class="fas fa-heart"></i>
                                        </a>
                                    </li>
                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                    <li>
                                        <a href="#" class="action to-compare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product) ?>'> 
                                        <i class="fas fa-balance-scale"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            <?= strpos($pos, $viewMode . '-secondary') ?
                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                            ) : '' ?>

                        <?php else:?>
                            <?php // Product Image ?>
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                            class="product photo product-item-photo"
                            tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                        <?php endif; ?>
                    </div>

                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
                        <?php if ($showDescription): ?>
                            <div class="product description product-item-description">
                                <?= /* @noEscape */ $_helper->productAttribute(
                                    $_product,
                                    $_product->getShortDescription(),
                                    'short_description'
                                ) ?>
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                    title="<?= /* @noEscape */ $_productNameStripped ?>"
                                    class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                            </div>
                        <?php endif; ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()):?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                              action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?=
                                                   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary btn btn-tocart"
                                                    disabled>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else:?>
                                        <?php if ($_product->isAvailable()):?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?= strpos($pos, $viewMode . '-primary') ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                    ) : '' ?>

                                <?php if ($viewMode === 'list'): ?>
                                    <div data-role="add-to-links" class="actions-secondary">
                                    <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="action to-wish-list" data-action="add-to-wishlist">
                                        <i class="fas fa-heart"></i>
                                    </a>
                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                    <a href="#" class="action to-compare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product) ?>'> 
                                        <i class="fas fa-balance-scale"></i>
                                    </a>
                                    </div>

                                <?= strpos($pos, $viewMode . '-secondary') ?
                                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                    $position,
                                    'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                ) : '' ?>
                                <?php endif;?>

                            </div>
                        </div>
                    </div>
                </div>
                <?= strpos($pos, $viewMode . '-actions') ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
