<script type="text/x-magento-init">
{
    "#bannerSlider": {
        "myslider": {
            "selector":".swiper-container",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "infinite": false,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
}
</script>


<?php
/**
 * Init Our products Slider
 */
?>

<script type="text/x-magento-init">
{
    "#ourProducts": {
        "myslider": {
            "selector":"#ourProducts .product-items",
            "sliderOptions":{
                "slidesToShow": 4,
                "slidesToScroll": 4,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": 3,
                            "slidesToScroll": 3
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 2
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
}
</script>

<script type="text/x-magento-init">
    {
        "#categoryProducts": {
            "myslider": {
                "selector":".category-product-container .product-items",
                "sliderOptions":{
                    "dots": false,
                    "arrows": true,
                    "rows": 3,
                    "slidesToShow": 1,
                    "slidesToScroll": 1,
                    "responsive": [
                        {
                            "breakpoint": 1024,
                            "settings": {
                                "slidesToShow": 2,
                                "slidesToScroll": 1
                            }
                        },
                        {
                            "breakpoint": 640,
                            "settings": {
                                "slidesToShow": 1,
                                "slidesToScroll": 1
                            }
                        }
                    ]
                }
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
    ".news-blog": {
        "myslider": {
            "selector":".news-blog-wrapper",
            "sliderOptions":{
                "slidesToShow": 3,
                "slidesToScroll": 3,
                "responsive": [
                    {
                        "breakpoint": 992,
                        "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 2
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
    }
</script>


<script type="text/x-magento-init">
    {
    ".shop-by-brands": {
        "myslider": {
            "selector":".brands-container",
            "sliderOptions":{
                "slidesToShow": 5,
                "slidesToScroll": 1,
                "centerMode": true,
                "centerPadding": 0,
                "dots": true,
                "autoplay": true,
                "responsive": [
                    {
                        "breakpoint": 992,
                        "settings": {
                            "slidesToShow": 4
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 3
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }
    }
    }
</script>